---
deployment:
 tasks:
 - export DEPLOYPATH=/home2/johnsmi1/responsive-resume.johnsmillie.tech
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp -R img $DEPLOYPATH
 - /bin/cp -R css $DEPLOYPATH
 - /bin/cp -R js $DEPLOYPATH
